import { NgModule } from '@angular/core';
import {
  MatButtonModule,
  MatCheckboxModule,
  MatIconModule,
  MatFormFieldModule,
  MatInputModule,
  MatSidenavModule,
  MatToolbarModule,
  MatListModule,
  MatTabsModule,
  MatTableModule,
  MatPaginatorModule,
  MatCardModule,
  MatSelectModule,
  MatOptionModule,
  MatGridListModule,
  MatSnackBarModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatTooltipModule,
  MatAccordion,
  MatExpansionModule,
  MatStepperModule,
  MatAutocompleteModule,
  MatRadioModule,
  MatDialogModule,
  MatMenuModule,
  MatProgressSpinnerModule,
    } from '@angular/material';

@NgModule({
  imports: [MatButtonModule,
            MatCheckboxModule,
            MatIconModule,
            MatFormFieldModule,
            MatInputModule,
            MatSidenavModule,
            MatToolbarModule,
            MatListModule,
            MatTabsModule,
            MatTableModule,
            MatPaginatorModule,
            MatCardModule,
            MatSelectModule,
            MatOptionModule,
            MatGridListModule,
            MatSnackBarModule,
            MatDatepickerModule,
            MatNativeDateModule,
            MatTooltipModule,
            MatSidenavModule,
            MatExpansionModule,
            MatStepperModule,
            MatAutocompleteModule,
            MatRadioModule,
            MatDialogModule,
            MatMenuModule,
            MatIconModule,
            MatProgressSpinnerModule,
            

          ],
  exports: [MatButtonModule,
            MatCheckboxModule,
            MatIconModule,
            MatFormFieldModule,
            MatInputModule,
            MatSidenavModule,
            MatToolbarModule,
            MatListModule,
            MatTabsModule,
            MatTableModule,
            MatPaginatorModule,
            MatCardModule,
            MatSelectModule,
            MatOptionModule,
            MatGridListModule,
            MatSnackBarModule,
            MatDatepickerModule,
            MatNativeDateModule,
            MatTooltipModule,
            MatSidenavModule,
            MatExpansionModule,
            MatStepperModule,
            MatAutocompleteModule,
            MatRadioModule,
            MatDialogModule,
            MatMenuModule,
            MatIconModule,
            MatProgressSpinnerModule


          ]
})
export class MaterialModule {}